background_opacity 0.8

window_padding_width 12
window_margin_width 0

font_family JetBrains Mono
font_size 12

foreground #cbbab0
color0  #2a2826
color1  #671b1c
color2  #ccc2bd
color3  #ccc2bd
color4  #7a8fa6
color5  #a68fa0
color6  #8fa8a0
color7  #ccc2bd

color8  #4a4541
color9  #864040
color10 #ccc2bd
color11 #ccc2bd
color12 #8fa0b8
color13 #b8a0b0
color14 #a0b8b0
color15 #e0d0c8

cursor #cbbab0
cursor_text_color black

