general {
    lock_cmd = ""
    before_sleep_cmd = ""
    after_sleep_cmd = ""
}

listener {
    timeout = 950   
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
